"""Ajout camera_url à Court

Revision ID: 83d55082619c
Revises: 
Create Date: 2025-07-10 15:44:24.101403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83d55082619c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('court', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_url', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('court', schema=None) as batch_op:
        batch_op.drop_column('camera_url')

    # ### end Alembic commands ###
